### ISSUE TITLE
Errors when attempting to display the circuit

### ISSUE THREAD

**Issue by ninaoneill** [myQLM/myqlm-issues#13]
**Describe the bug**
Errors when attempting to display the circuit

**To Reproduce**
When running the epr_pair tutorial, I tried to print the circuit using %qatdisplay and obtained a Permission Error. An image file of the circuit was created but it had 0 bytes. I also tried to print the circuit using %jsqatdisplay and obtained a Javascript error. Again, an image file of the circuit was created but it had 0 bytes. 

**Expected behavior**
I expected the circuit to be printed, as is shown in the tutorial.

**Screenshots**
Added below

**Desktop (please complete the following information):**
Windows 10, Firefox 91.0.2 (64 bit)

![Capture1](https://user-images.githubusercontent.com/61952878/131194623-79953cce-b113-4c51-ad2d-0844ea7d1ef1.PNG)
![Capture2](https://user-images.githubusercontent.com/61952878/131194323-cb23f03a-9bb5-46d4-a22c-d6b26e09a1a2.PNG)

**Comment by amitsaha2806** [comment]
Hello @ninaoneill,

Have you installed myQLM magics to display quantum circuits inside Jupyter notebooks?

Please let me know.

**Comment by ninaoneill** [comment]
Hello,

Yes, I have installed myQLM magic. It said the installation was successful.

**Comment by amitsaha2806** [comment]
Hello @ninaoneill,

Could you please post your complete program?

**Comment by ninaoneill** [comment]
Hello, I was attempting to run the epr_pair program available in the
tutorial notebooks. I sent it as an attachment in this e-mail.

Em ter, 31 de ago de 2021 06:07, amitsaha2806 ***@***.***>
escreveu:

**Comment by amitsaha2806** [comment]
Hello,

I have tried to run EPR_pair on Windows 10, Firefox 91.0.2 (64 bit). But, in my case, it has successfully printed the desired circuit.

![image](https://user-images.githubusercontent.com/58389485/131613224-e0d1647a-ef31-43ba-9453-51ebd77052f6.png)

Before running your program again, please make sure you have installed every prerequisite properly. Please let me know if everything is properly installed at your end and still you are not getting the circuit output.

**Comment by ninaoneill** [comment]
I've successfully installed myqlm, Imagemagick and myqlm magics, but I
still have the same error. Is there anything else that must be installed?

**Comment by jcjaskula** [comment]
Hi @ninaoneill,

I believe `%qatdisplay --svg circuit` would work. It will display your circuit using other libraries (no installation required).

**Comment by ninaoneill** [comment]
Hello,

It worked. Thank you very much :)
