### ISSUE TITLE
Issue magic command

### ISSUE THREAD

**Issue by jbaraujo** [myQLM/myqlm-issues#15]
Hi, I am trying to visualize circuits in myQLM. The problem is in installing the magic commands.
*I'm using a M1 Mac with OS Monterrey*

When I try the command provided, I get

python -m qat.magics.install
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: **No module named qat.magics**

Has anyone faced the same issue?

Thank you!

**Comment by amitsaha2806** [comment]
Hello,

Can you please update your python first and then try to install the magic.

Please go through the prerequisite again : https://myqlm.github.io/myqlm_specific/install.html

Please make sure that everything is set up as per the need.

Thanks.

**Comment by jbaraujo** [comment]
Thank you, Ami!

I did it as you suggested but it still tells me **no module named qat.magics was found** :(

Windows machines seem to face the same problem,

Again, thank you for your time!

**Comment by amitsaha2806** [comment]
Hello,

Did you install **ImageMagick for wand**?

You can install it from following link:
(http://docs.wand-py.org/en/0.6.6/guide/install.html)

Thanks.

**Comment by sopalain** [comment]
Hi ,

I used Monterey 12.2.1 with python 3.8.10, as said by Amit, after installing Imagemagik for wand, I had the followig the output : 
macbook-pro-sop:~ alainmassiot$ python -m qat.magics.install
QLM magics have been sucessfully installed


Regards 

Let us know whether things went right.
