### ISSUE TITLE
Error in qftarith.add_const method

### ISSUE THREAD

**Issue by ghost** [myQLM/myqlm-issues#16]
**Describe the bug**
I am using `qftarith` to perform arithmetic operations on `QInt` registers but the `add_const` operation does not work properly.
I'm afraid a muddle has been made between MSB and LSB convention.
According to [this documentation](https://myqlm.github.io/qat-lang-arith.html?highlight=add_const#qat.lang.AQASM.qftarith.add_const), the `add_const(reg_size, constant)` should build a circuit performing an addition by a constant: $|a\rangle \mapsto |a + C\rangle$ but the result is not as expected.

**To Reproduce**
The following code shows the problem :
```
from qat.lang.AQASM import Program
import qat.lang.AQASM.qftarith as qftarith
from qat.lang.AQASM.qint import QInt
from qat.qpus import get_default_qpu

qprog = Program()
qbits = qprog.qalloc(size=5, class_type=QInt)

qbits.set_value(4)
qprog.apply(qftarith.add_const(5, 1), qbits)

for sample in get_default_qpu().submit(qprog.to_circ(link=[qftarith]).to_job()):
    print("State %s: probability %s, amplitude %s" % (sample.state, sample.probability, sample.amplitude))
```

The result should be 4 + 1 = 5 but the effective result is 20 :
`State |20>: probability 0.9999999999999982, amplitude (0.9999999999999991-8.304471026264037e-17j)`

**Expected behavior**
I'm afraid the `add_const` circuit does not perform the operation with the same bit numbering than the `set_value` circuit.
If we set the initial value to 0 on a 5-qubits QInt register and performs `add_const(5, 3)`, we should obtain the $|3\rangle = |2^0 + 2^1\rangle$ state but we get $ |24\rangle = |2^4 + 2^3\rangle $ instead.
The documentation does not provide any indication (like additional parameters) to change the bit numbering of the add_const method).

**Screenshots**
![image](https://user-images.githubusercontent.com/48211643/170277976-6dbca5c9-e878-427f-9f7b-500fa0556419.png)

**Additional context**
Version of myqlm and qat packages :
```
myqlm==1.5.1 (latest)
myqlm-simulators==1.5.1 (latest)
qat-comm==1.3.4 (latest)
qat-core==1.5.1 (latest)
qat-devices==0.1.5 (latest)
qat-lang==2.1.3 (latest)
qat-variational==1.3.3 (latest)
```

[Edit] : I made a mistake in the vocabulary I used. The problem I wanted to point was on the bit numbering and obviously not the endianness (bytes ordering).

**Comment by ArnaudAtos** [comment]
Dear @mullonch

Type `QInt` will encode the integer using the msb convention. Nevertheless, routine `add_const(5, 1)` assumes that the lsb convention is used (leading to the invalid output you spotted).

If I reuse your example:

```python
from qat.lang.AQASM import Program
import qat.lang.AQASM.qftarith as qftarith
from qat.lang.AQASM.qint import QInt
from qat.qpus import get_default_qpu

qprog = Program()
qbits = qprog.qalloc(size=5, class_type=QInt)

qbits.set_value(4)
qprog.apply(qftarith.add_const(5, 1), qbits)

for sample in get_default_qpu().submit(qprog.to_circ(link=[qftarith]).to_job()):
    print(f"State {sample.state}: bitstring {sample.state.bitstring}")
```

The final state is `|10100>` which could be decoded as:
 - `|20>` using msb convention
 - `|5>` using lsb convention

I would recommend to directly use the `+=` operator that uses the right convention:

```python
from qat.lang.AQASM import Program
import qat.lang.AQASM.qftarith as qftarith
from qat.lang.AQASM.qint import QInt
from qat.qpus import get_default_qpu

qprog = Program()
qbits = qprog.qalloc(size=5, class_type=QInt)

qbits.set_value(4)
qbits += 1  # Performs ADD_CONST using

for sample in get_default_qpu().submit(qprog.to_circ(link=[qftarith]).to_job()):
    print("State %s: probability %s, amplitude %s" % (sample.state, sample.probability, sample.amplitude))
```

The output of this sample of code is:

```
State |5>: probability 0.9999999999999982, amplitude (0.9999999999999991-8.304471026264037e-17j)
```

**Comment by ghost** [comment]
Dear @ArnaudAtos , 
Yes, the difference between bit numbering convention is what I realized but I thought it was a mistake.

So, if it is not the case :
- Is there a `QRegister` type that is equivalent to the `QInt` type but using the LSB convention ?

- If I want to create circuit with the controlled version of the addition routine, do i have to specify a `QRoutine` in which I perform the addition and control it or is there already some MSB add_const routine i can control directly ?

**Comment by ArnaudAtos** [comment]
You can force the LSB convention by adding a `reverse_bit_convention=True` when allocating qubits. Your code would look like:

```python
from qat.lang.AQASM import Program
import qat.lang.AQASM.qftarith as qftarith
from qat.lang.AQASM.qint import QInt
from qat.qpus import get_default_qpu

qprog = Program()
qbits = qprog.qalloc(size=5, class_type=QInt, reverse_bit_order=True)

qbits.set_value(4)
qprog.apply(qftarith.add_const(5, 1), qbits)

for sample in get_default_qpu().submit(qprog.to_circ(link=[qftarith]).to_job()):
    print(f"State {sample.state}: bitstring {sample.state.bitstring}")
```

To perform the control, you can:
 - update the previous sample of code, by replacing `qftarith.add_const(5, 1)` by `qftarith.add_const(5, 1).ctrl()`
 - use the `*` operator (cf. bellow)

```python
from qat.lang.AQASM import Program
import qat.lang.AQASM.qftarith as qftarith
from qat.lang.AQASM.qint import QInt
from qat.qpus import get_default_qpu

qprog = Program()
ctrl = qprog.qalloc(1, QInt)
qbits = qprog.qalloc(size=5, class_type=QInt)

qbits.set_value(4)
qbits += ctrl * 1  # Replace the "1" by the constant value you want to add

for sample in get_default_qpu().submit(qprog.to_circ(link=[qftarith]).to_job()):
    print("State %s: probability %s, amplitude %s" % (sample.state, sample.probability, sample.amplitude))
```

The generated circuit looks like:

```txt
─────●───────────────
     │
     │
    ┌┴──────────────┐
────┤               ├
    │               │
    │               │
    │               │
────┤               ├
    │               │
    │               │
 ┌─┐│               │
─┤X├┤ADD_CONST[5, 1]├
 └─┘│               │
    │               │
    │               │
────┤               ├
    │               │
    │               │
    │               │
────┤               ├
    └───────────────┘
```
