### ISSUE TITLE
Install fails on arm64 Linux in multipass on M1 Mac

### ISSUE THREAD

**Issue by cryptohgb** [myQLM/myqlm-issues#17]
**Describe the bug**
Unable to pip install the myqlm package.

**To Reproduce**
- Fresh Ubuntu 20.4 installation in ARM64 Linux via multipass on M1 Mac
- pyenv and imagemagick installed

> pyenv install 3.6.15
> pyenv global 3.6.15

> pip install Wand

> pip install jupyter

> pip install myqlm
Collecting myqlm
  Using cached myqlm-1.5.1-py3-none-any.whl (2.0 kB)
  Using cached myqlm-1.5.0-py3-none-any.whl (2.0 kB)
Collecting myqlm-simulators>=1.5.0
  Using cached myqlm_simulators-1.5.1-py3-none-any.whl (19 kB)
Collecting myqlm
  Using cached myqlm-1.4.1-py3-none-any.whl (2.0 kB)
  Using cached myqlm-1.4.0-py3-none-any.whl (2.0 kB)
  Using cached myqlm-1.2.3-py3-none-any.whl (2.0 kB)
  Using cached myqlm-1.2.2-py3-none-any.whl (2.0 kB)
  Using cached myqlm-1.1.6-py3-none-any.whl (1.8 kB)
  Using cached myqlm-1.1.5-py3-none-any.whl (1.6 kB)
ERROR: Cannot install myqlm==1.1.5, myqlm==1.1.6, myqlm==1.2.2, myqlm==1.2.3, myqlm==1.4.0, myqlm==1.4.1, myqlm==1.5.0 and myqlm==1.5.1 because these package versions have conflicting dependencies.
The conflict is caused by:
    myqlm 1.5.1 depends on qat-core>=1.5.1
    myqlm 1.5.0 depends on qat-devices>=0.1.3
    myqlm 1.4.1 depends on qat-devices>=0.1.3
    myqlm 1.4.0 depends on qat-core>=1.4.0
    myqlm 1.2.3 depends on qat-core>=1.3.3
    myqlm 1.2.2 depends on qat-comm>=1.2.0
    myqlm 1.1.6 depends on qat-variational>=1.1.6
    myqlm 1.1.5 depends on qat-core>=1.2.5
To fix this you could try to:
_1. loosen the range of package versions you've specified
_2. remove package versions to allow pip attempt to solve the dependency conflict
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

The same problem occurs with Python 3.9. Not tested other Python versions (not supported by myqlm on Linux).

Trying to install version 1.5.1 of myqlm, explicitly, gives:

> pip install myqlm==1.5.1
Collecting myqlm==1.5.1
  Downloading myqlm-1.5.1-py3-none-any.whl (2.0 kB)
ERROR: Could not find a version that satisfies the requirement qat-comm>=1.3.3 (from myqlm) (from versions: none)
ERROR: No matching distribution found for qat-comm>=1.3.3

**Expected behavior**
Install of myqlm package without error.

**Comment by ArnaudAtos** [comment]
Dear @cryptohgb 

Unfortunatly, ARM64 architecture is only supported for *MacOS*
myQLM for *Linux* and *Windows* only support X86_64 architectures

The documentation of the next release of myQLM will be updated to highlight this limitation
