### ISSUE TITLE
Syntax error in "Advanced programming using pyAQASM" documentation

### ISSUE THREAD

**Issue by diatomicDisaster** [myQLM/myqlm-issues#18]
There appears to be a simple syntax error (a missing `(` bracket) in one of the examples in the documentation. This causes the expected output not to appear correctly, instead rendering an error message.

It appears under the subsection '[Subcircuit definition](https://myqlm.github.io/advanced_programming.html?highlight=ancillae#subcircuit-definition)' in the 'Advanced programming using pyAQASM' page.

![image](https://user-images.githubusercontent.com/56824415/183597726-a1cf4e66-7a28-4d77-be76-76408d5c771b.png)

**Comment by tayral** [comment]
Hello @diatomicDisaster 
Thanks for pointing this out, it will be fixed in the next version.
