### ISSUE TITLE
Could not able to install myqlm using pip

### ISSUE THREAD

**Issue by boldneutron** [myQLM/myqlm-issues#19]
**Describe the bug**
while install with 'pip install myqlm' I got this

**Expected behavior**
I have not installed any version of myqlm before. I guess it is a conflict problem.

**Screenshots**
![Screenshot (240)](https://user-images.githubusercontent.com/104217000/189089324-5783f38d-adb0-4cd7-89fb-f58465f8a3c8.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Python - 3.10

**Comment by ArnaudAtos** [comment]
Dear @boldneutron 
Unfortunatly, myQLM is not supported for Python 3.10 (cf. [compatibility matrix from the doc](https://myqlm.github.io/myqlm_specific/install.html#compatibility-matrix)).
This limitation should be fixed soon. Please try to install myQLM using an older version of Python
