### ISSUE TITLE
qat.devices depends on networkx<3.0 (Ubuntu 22.04)

### ISSUE THREAD

**Issue by Gistbatch** [myQLM/myqlm-issues#21]
**Describe the bug**
When setting up a device architecture with an incompatible version of networkx the program fails due to:
```
from qat.devices import LineDevice
File "__init__.py", line 155, in init qat.devices.__init__
File "rigetti.py", line 31, in init qat.devices.rigetti
AttributeError: module 'networkx' has no attribute 'from_numpy_matrix'
```
on Python 3.10

**To Reproduce**
1. Set up a new Python environment and install the packages `pip install qlmaas myqlm`
2. Run a Python shell
3. Import a device e.g. `from qat.devices import LineDevice`

**Expected behavior**
When installing the correct dependencies are pulled in. 

**Screenshots**
Not applicable.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Python: 3.10.6

**Additional context**
None.

**Comment by ArnaudAtos** [comment]
Dear @Gistbatch,
myQLM 1.9 has been released recently. Module qat-devices does not rely on networkx < 3.0 anymore
