### ISSUE TITLE
Issues with installation myqlm on MacOS

### ISSUE THREAD

**Issue by raksharuia** [myQLM/myqlm-issues#22]
** cannot install the latest release - **v1.9.2** 
** previous version installs but does not work without installing `jax` and `jaxlib` manually
** autotests on GitHub designed for MacOS fails.

**Comment by JayaPoluri** [comment]
Hi Raksha,
Try using 1.9.4 our latest release, if you still face the issue, please feel free to reopen the issue and I will try to help.
