### ISSUE TITLE
qat.qpus not working

### ISSUE THREAD

**Issue by Buffoni** [myQLM/myqlm-issues#29]
After upgrading myqlm to the latest version 1.9.4 (qat-core 1.8.2) when trying to import any module of qat.qpus (LinAlg or other solvers and also functions like get_default_qpu) it returns a "Module not found" error.
The machine is running Ubuntu with Python 3.9.16 .

**Comment by JayaPoluri** [comment]
Hi Buffoni,
we need more information about what version of Ubuntu (for Ubuntu we only support 22.4 and above) you are using and screenshot of the code and resulting traceback error.

**Comment by Buffoni** [comment]
Ubuntu version 21.04 the code and traceback

`from qat.qpus import LinAlg`
ImportError: cannot import name 'LinAlg' from 'qat.qpus'

**Comment by JayaPoluri** [comment]
Hi Buffoni, we only support myqlm for Ubuntu version 22.4 or greater. Please try to upgrade the Ubuntu.
