### ISSUE TITLE
Add Python 3.7, 3.8, 3.9 support for myqlm

### ISSUE THREAD

**Issue by bartleyg** [myQLM/myqlm-issues#3]
**Is your feature request related to a problem? Please describe.**
myqlm cannot be installed on Python 3.7+
```
$ pip install myqlm
Collecting myqlm
  Using cached myqlm-1.1.6-py3-none-any.whl (1.8 kB)
ERROR: Could not find a version that satisfies the requirement qat-comm>=1.1.6 (from myqlm) (from versions: none)
ERROR: No matching distribution found for qat-comm>=1.1.6 (from myqlm)
```

Please consider supporting Python 3.7, 3.8, & 3.9 as Python 3.6 is very old. Python 3.6 & 3.7 are in security only maintenance while Python 3.8 & 3.9 are in bugfix maintenance. In addition, Python 3.6 will end of life in a year.

See https://devguide.python.org/#status-of-python-branches

**Comment by SaikatBasu90** [comment]
We are already working on it. Sorry for the inconvenience.

**Comment by amitsaha2806** [comment]
Hello,

The new version of myQLM 1.2.2 has already been released. This new version is compatible with Windows (Python 3.6, 3.7 and 3.8), Linux (Python 3.6 and 3.8) and MacOS X (Python 3.6, 3.7 and 3.8). Thank you.

**Comment by bartleyg** [comment]
@amitsaha2806 thanks for the update. I see that Python 3.7 on Linux was not included. Are there plans to release a version for that?

**Comment by Petitjean971** [comment]
When I try to install myqlm, i get this message :
`$ pip install myqlm
Defaulting to user installation because normal site-packages is not writeable
Collecting myqlm
  Using cached myqlm-1.2.2-py3-none-any.whl (2.0 kB)
Collecting myqlm-simulators>=1.2.0
  Downloading myqlm_simulators-1.2.0-py3-none-any.whl (19 kB)
ERROR: Could not find a version that satisfies the requirement qat-lang>=2.0.0 (from myqlm) (from versions: none)
ERROR: No matching distribution found for qat-lang>=2.0.0 (from myqlm)
`
What should I do ?

**Comment by amitsaha2806** [comment]
@Petitjean971 May I know the details of your operating system on which you are trying to install myQLM?

**Comment by Petitjean971** [comment]
Here are the detail of my operating system

>Linux goldenticket 4.19.163-1-MANJARO #1 SMP Fri Dec 11 17:21:11 UTC 2020 x86_64 GNU/Linux

**Comment by amitsaha2806** [comment]
@Petitjean971 which version of python you are using?

**Comment by Petitjean971** [comment]
Python 3.9.1
I force the use of Python 3.8.7 to work as a temporary solution.

**Comment by amitsaha2806** [comment]
Is it working now with python 3.8.7?
or still you are getting same error?

**Comment by Petitjean971** [comment]
No with Python 3.8.7 everything is fine.

**Comment by amitsaha2806** [comment]
Ok Thank you for using myQLM @Petitjean971

**Comment by Petitjean971** [comment]
Do you know when will be the release for Python 3.9 ?

**Comment by amitsaha2806** [comment]
We are working on it. We will update it once it is done.

**Comment by Petitjean971** [comment]
Thank you for these answers.
Good luck.
