### ISSUE TITLE
installation error on a windows 7 environment

### ISSUE THREAD

**Issue by philippe3263** [myQLM/myqlm-issues#4]
hi
the installation on a PC with windows 7 leads to the following error : 
pip install myqlm
Collecting myqlm
  Using cached myqlm-1.1.6-py3-none-any.whl (1.8 kB)
  Using cached myqlm-1.1.5-py3-none-any.whl (1.6 kB)
ERROR: Cannot install myqlm==1.1.5 and myqlm==1.1.6 because these package versio
ns have conflicting dependencies.

The conflict is caused by:
    myqlm 1.1.6 depends on qat-comm>=1.1.6
    myqlm 1.1.5 depends on qat-core>=1.2.5

the problem appears with python 3.8 and several others versions... I have tested 3.8.5 ...

Do you have a solution ? An idea of the problem ? of course the I failed to install the qat-comm and qat-core ....

Regards

**Comment by SaikatBasu90** [comment]
It seems that myQLM conflicts with himself. I guess your are trying to update myQLM on a machine having myQLM already installed. If we're right, can you try to type the following command:
$> pip install -U myqlm

**Comment by philippe3263** [comment]
Hi
it does not solve the problem.

...................................>pip install -U myqlm
Collecting myqlm
  Using cached myqlm-1.1.6-py3-none-any.whl (1.8 kB)
  Using cached myqlm-1.1.5-py3-none-any.whl (1.6 kB)
ERROR: Cannot install myqlm==1.1.5 and myqlm==1.1.6 because these package versio
ns have conflicting dependencies.

The conflict is caused by:
    myqlm 1.1.6 depends on qat-comm>=1.1.6
    myqlm 1.1.5 depends on qat-variational>=1.1.5

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

:(

**Comment by ArnaudGazda** [comment]
Hi,

I don't know why but pip is trying to install two different versions of myQLM (version 1.1.5 and version 1.1.6). The pip command is not supposed to install several versions of the same module (except in specific cases, but not by default).

Have you installed several versions of myQLM? 

- If myQLM is not installed on your machine (you can check by typing `pip show myqlm`), you can force pip to install the latest version of myQLM by typing the command `pip install myqlm==1.1.6`
- If myQLM is installed on your machine, maybe several versions are conflicting. If you can, uninstalling myQLM (all installed versions) before reinstalling myQLM could solve your issue

I hope this answer may help :-)
