### ISSUE TITLE
qlm_to_cirq fails silently for circuits with symbolic variables

### ISSUE THREAD

**Issue by pmirallesr** [myQLM/myqlm-issues#8]
**Describe the bug**
qlm_to_cirq fails silently for circuits with symbolic variables - No error is raised but printing the result produces an exception.

**To Reproduce**
On a fresh myQLM install, run this example script:
```
from qat.interop.cirq import qlm_to_cirq
from qat.qpus import get_default_qpu
from qat.lang.AQASM import Program, RY, RZ
import numpy as np

prog = Program()
qbits = prog.qalloc(3)

variable = prog.new_var(float, "a")
for qbit in qbits:
    RY(variable)(qbit)
    RZ(4*variable)(qbit)

cirq = prog.to_circ()
google_cirq = qlm_to_cirq(cirq)
print(google_cirq)

```
**Expected behavior**
A schema like this one but with Ry(a) and Rz(4*a)
![image](https://user-images.githubusercontent.com/52211742/110351029-a92ebf80-8034-11eb-9138-a5b2542b9ece.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Firefox
 - Version 86

**Additional context**
Tensorflow Quantum seems to print this properly, and I'm concerned the inability to print may point to a deeper problem with exporting myQLM circuits with symbolic variables to cirq

EDIT: Other cirq operations also produce errors such as this one:
```
from qat.interop.cirq import qlm_to_cirq
from qat.qpus import get_default_qpu
from qat.lang.AQASM import Program, RY, RZ
import numpy as np
from cirq.contrib.svg import SVGCircuit
import cirq
import sympy

# myQLM circuit
prog = Program()
qbits = prog.qalloc(3)
variable = prog.new_var(float, "a")
for qbit in qbits:
    RY(variable)(qbit)
    RZ(4*variable)(qbit)
circ = prog.to_circ()

# Export to cirq
google_circ = qlm_to_cirq(circ)

# Manipulate with cirq
a = sympy.symbols('a')
resolver = cirq.ParamResolver({a: 0.5})
output_state_vector = cirq.Simulator().simulate(
    google_circ, resolver).final_state_vector
print(output_state_vector)
```

EDIT 2: The error occurs both with cirq versions 0.8.2 and 0.9.1.

**Comment by SaikatBasu90** [comment]
Hello @pmirallesr  
I have tried to reproduce the scenario. fortunately it is giving me the expected output (I have used myQLM version 1.2.2, cirq version 0.8.2, OS Ubuntu 20.04). Could you please confirm the myQLM version you are using?

**Comment by jcjaskula** [comment]
Hi Pablo,

This was a limitation of the cirq interoperability module. I pushed a commit in myqlm-interop that should solve it. We will release a new version on pypi as soon as possible.
